Trello 977 compliance page
ministryofjustice/hmpps-manage-supervisions pull request #417
Opened 2021-11-22 15:55 UTC by dnyanesh-sonwane

'Select yes if attended and the outcome was acceptable'

2021-11-22 17:35 UTC, electrified approved these changes

2021-11-22 17:35 UTC, electrified commented on cypress/integration/record-outcome/record-outcome.spec.ts
> +      .shouldDisplayComplianceErrors('There is a problem', 'Select yes if attended and the outcome was acceptable')
This validation message doesn't use the style of wording I would expect... Guessing it was put in as a placeholder. One to query with the design team.

2021-11-22 18:08 UTC, dnyanesh-sonwane commented on cypress/integration/record-outcome/record-outcome.spec.ts
> +      .shouldDisplayComplianceErrors('There is a problem', 'Select yes if attended and the outcome was acceptable')
Updated the validation text message o indicate user must select an option.

2021-11-22 18:12 UTC, electrified requested changes

2021-11-22 18:12 UTC, electrified commented on cypress/integration/record-outcome/record-outcome.spec.ts
> +      .shouldDisplayComplianceErrors('There is a problem', 'Select one of the compliance option')
This should be pluralised: "Select one of the compliance option**s**" Sorry to nit pick :D

2021-11-22 18:27 UTC, electrified commented on src/server/record-outcome/view-model-factory/view-model-factory.service.ts
> +      compliance: body?.compliance,
This needs to get the value from the body, or from the session.

Otherwise the value won't be populated when you return to the page via the back link etc.

2021-11-23 08:04 UTC, fofr commented on cypress/integration/record-outcome/record-outcome.spec.ts
> +      .shouldDisplayComplianceErrors('There is a problem', 'Select one of the compliance option')
I wonder if this error message could be improved? 🤔

2021-11-23 08:33 UTC, dnyanesh-sonwane commented on cypress/integration/record-outcome/record-outcome.spec.ts
> +      .shouldDisplayComplianceErrors('There is a problem', 'Select one of the compliance option')
done

2021-11-23 08:33 UTC, dnyanesh-sonwane commented on src/server/record-outcome/view-model-factory/view-model-factory.service.ts
> +      compliance: body?.compliance,
done

2021-11-23 09:08 UTC, electrified approved these changes

2021-11-23 09:09 UTC, merged

2021-11-23 09:49 UTC, dnyanesh-sonwane commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance page](https://trello.com/c/puPRox76/977-compliance-page)

2021-11-23 09:50 UTC, dnyanesh-sonwane commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance page](https://trello.com/c/puPRox76/977-compliance-page)

2021-11-23 09:50 UTC, dnyanesh-sonwane commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance page](https://trello.com/c/puPRox76/977-compliance-page)